"""add key column to product image

Revision ID: cfd397afed77
Revises: 7d8486b5bb86
Create Date: 2026-07-24 09:47:39.346217

"""

import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cfd397afed77"
down_revision: Union[str, Sequence[str], None] = "7d8486b5bb86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "productimage",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("productimage", "key")
    # ### end Alembic commands ###
